[package]
name = "unitycatalog-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "unitycatalog-server"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["trace", "serde", "serde_json", "env-filter"]}

